const data = {
  products: [
    {
      name: 'Nike_Tshirt',
      slug: 'nike-slim',
      category: 'Tshirt',
      image: '/images/p1.jfif',
      price: '$210',
      countInstock: 10,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'OP shirt',
    },
    {
      name: 'Nike_tshirt',
      slug: 'fit-tshirt',
      category: 'Tshirt',
      image: '/images/p2.jpg.jfif',
      price: '$200',
      countInstock: 0,
      brand: 'nike',
      rating: 4.6,
      numReviews: 10,
      description: 'OP shirt',
    },
    {
      name: 'Puma_Tshirt',
      slug: 'Awesome',
      category: 'Tshirt',
      image: '/images/p3.jpg.jfif',
      price: '$180',
      countInstock: 10,
      brand: 'puma',
      rating: 10,
      numReviews: 10,
      description: 'OP',
    },
    {
      name: 'MG_Tshirt',
      slug: 'Swaggy',
      category: 'Tshirt',
      image: '/images/p4.jpg.jfif',
      price: '$320',
      countInstock: 10,
      brand: 'Morris Garages',
      rating: 10,
      numReviews: 10,
      description: 'OP',
    },
  ],
};

export default data;
